language: php
php:
  - 5.5
  - 5.4
  - 5.3

before_script:
  - mysql -e 'create database IF NOT EXISTS ukrcms_core_test;create database IF NOT EXISTS ukrcms_core_test';
  - composer self-update && composer --version
  - composer update --dev

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

script: phpunit --coverage-clover=coverage.clover --configuration dev/phpunit.xml dev/UcTests

notifications:
  email:
    - dev@funivan.com